# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr install collection-latexrecommended
    - tlmgr install collection-fontsrecommended
    - tlmgr install letltxmacro
    - tlmgr install wasysym
    - tlmgr install yfonts
    - tlmgr install xypic

language: R
cache: packages
branches:
  only:
  - master
  - /^issue-.*/
r_build_args: '--resave-data --compact-vignettes="both" '

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
